//
//  TransactionCandidate.swift
//  ExpenseManager
//
//  Created for Expense Manager iOS.
//  Normalized Transaction Pipeline Intermediate Representation.
//

import Foundation

/// Unified intermediate DTO generated by all ingestion channels (Manual, Smart Text, Voice, SMS, OCR)
/// prior to persistence into SwiftData.
public struct TransactionCandidate: Identifiable, Codable, Sendable, Equatable {
    public let id: UUID
    public var type: TransactionType
    public var amount: Decimal
    public var currencyCode: String
    public var merchantName: String
    public var categorySuggestion: String?
    public var accountSuggestion: String?
    public var destinationAccountSuggestion: String?
    public var paymentMethod: PaymentMethod?
    public var transactionDate: Date
    public var notes: String?
    public var tags: [String]
    public var source: InputSource
    public var sourceReference: String?
    public var confidence: ConfidenceScore
    public var needsReview: Bool
    public var warnings: [String]
    
    public init(
        id: UUID = UUID(),
        type: TransactionType = .expense,
        amount: Decimal = .zero,
        currencyCode: String = CurrencyFormatter.defaultCurrencyCode,
        merchantName: String = "",
        categorySuggestion: String? = nil,
        accountSuggestion: String? = nil,
        destinationAccountSuggestion: String? = nil,
        paymentMethod: PaymentMethod? = nil,
        transactionDate: Date = Date(),
        notes: String? = nil,
        tags: [String] = [],
        source: InputSource = .manual,
        sourceReference: String? = nil,
        confidence: ConfidenceScore = .manual,
        needsReview: Bool = false,
        warnings: [String] = []
    ) {
        self.id = id
        self.type = type
        self.amount = amount
        self.currencyCode = currencyCode
        self.merchantName = merchantName
        self.categorySuggestion = categorySuggestion
        self.accountSuggestion = accountSuggestion
        self.destinationAccountSuggestion = destinationAccountSuggestion
        self.paymentMethod = paymentMethod
        self.transactionDate = transactionDate
        self.notes = notes
        self.tags = tags
        self.source = source
        self.sourceReference = sourceReference
        self.confidence = confidence
        self.needsReview = needsReview || confidence.requiresReview
        self.warnings = warnings
    }
}
